#!/bin/bash

# create snuglive

install_snuglinux_func="/usr/share/snuglinux/install-snuglinux.func"

FILE_COFIG="/etc/snuglive.conf"

pkgs="install-snuglinux wget archiso arch-install-scripts awk dosfstools e2fsprogs findutils gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools"
pacman -Q $pkgs  > /dev/null
if [ "$?" != 0 ]; then
   pacman -S $pkgs
fi

if ! [ -f "${install_snuglinux_func}" ]; then
   exit 1
fi

source ${install_snuglinux_func}

if ! [ -f ${FILE_COFIG} ]; then
   show_message NOT_FOUND_CONFIG ${FILE_COFIG}
   exit 1
else
   source "${FILE_COFIG}"
fi

if ! [ -d "${PATCH_SNUGLIVE}" ]; then
  mkdir "${PATCH_SNUGLIVE}"
else
  show_message FAILED_TO_CREATE_DIR ${PATCH_SNUGLIVE}
  exit 1;
fi

cp -r /usr/share/archiso/configs/releng/* ${PATCH_SNUGLIVE}

echo "# snuglinux
aic94xx-firmware
wd719x-firmware
install-snuglinux" >> ${PATCH_SNUGLIVE}/packages.x86_64

sed -e "s|Arch Linux|Snug Linux|g" -i ${PATCH_SNUGLIVE}/profiledef.sh
sed -e "s|archlinux|snuglinux|g" -i ${PATCH_SNUGLIVE}/profiledef.sh
sed -e "s|ARCH_|SNUG_|g" -i ${PATCH_SNUGLIVE}/profiledef.sh

# fix
sed -e "s|termite-terminfo|alacritty|g" -i ${PATCH_SNUGLIVE}/packages.x86_64

rm ${PATCH_SNUGLIVE}/syslinux/splash.png

for f in "${PATCH_SNUGLIVE}/syslinux/*" ; do
    sed -e "s|Arch Linux|Snug Linux|g" -i  ${f}
done

edit_pacman_conf "${PATCH_SNUGLIVE}"

wget https://github.com/snuglinux/create-snuglive/raw/main/src/syslinux/splash.png -O ${PATCH_SNUGLIVE}/syslinux/splash.png

for f in "${PATCH_SNUGLIVE}/efiboot/loader/entries/*" ; do
    sed -e "s|Arch Linux|Snug Linux|g" -i  ${f}
done

#cp  /etc/locale.gen ${PATCH_SNUGLIVE}/airootfs/etc

wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/etc/passwd -O ${PATCH_SNUGLIVE}/airootfs/etc/passwd
wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/etc/hostname -O ${PATCH_SNUGLIVE}/airootfs/etc/hostname
wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/etc/vconsole.conf -O ${PATCH_SNUGLIVE}/airootfs/etc/vconsole.conf
wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/etc/locale.gen -O ${PATCH_SNUGLIVE}/airootfs/etc/locale.gen
wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/root/.bashrc -O ${PATCH_SNUGLIVE}/airootfs/root/.bashrc
wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/root/customize_airootfs.sh -O ${PATCH_SNUGLIVE}/airootfs/root/customize_airootfs.sh
wget https://github.com/snuglinux/create-snuglive/raw/main/src/airootfs/usr/local/bin/Installation_guide -O ${PATCH_SNUGLIVE}/airootfs/usr/local/bin/Installation_guide
wget https://github.com/snuglinux/create-snuglive/raw/main/src/build-snuglive.sh -O ${PATCH_SNUGLIVE}/build-snuglive.sh

chmod 755 ${PATCH_SNUGLIVE}/build-snuglive.sh
